version: "3.9"
networks:
  intranet:
    external: true 
volumes:
  botdata:
services:
  zarabot:
    image: node:14
    entrypoint: /bin/bash
    command: >
      -c 
      'npm i -g pm2;
      git clone https://github.com/debagger/shop-watcher-bot.git; 
      cd shop-watcher-bot && 
      npm i && 
      npm run build && 
      pm2 start --watch &&
      pm2 logs app'
    volumes:
      - botdata:/bot-data
    container_name: zarabot
    environment:
      - CHATS_DATA_DIR=/bot-data
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - APP_PORT=${APP_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    restart: always
    networks:
      - intranet
    expose:
      - "3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zarabot.rule=Host(`${HOST}`)"
      - "traefik.http.routers.zarabot.tls=true"
      - "traefik.http.routers.zarabot.tls.certresolver=leresolver"
      # - "traefik.http.routers.zarabot.middlewares=traefik-forward-auth"
