version: "3.9"
networks:
  intranet:
    external: true 
services:
  zarabot:
    image: node:14
    entrypoint: /bin/bash
    command: >
      -c 
      'npm i -g pm2;
      git clone https://github.com/debagger/shop-watcher-bot.git; 
      cd shop-watcher-bot && 
      npm i && 
      npm run build && 
      cd client/ &&
      npm i &&
      npm run build &&
      cd ../ &&
      pm2 start &&
      pm2 logs app'
    container_name: zarabot
    environment:
      - SHELL=/bin/bash
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - APP_PORT=${APP_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    restart: always
    networks:
      - intranet
    expose:
      - "${APP_PORT}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zarabot.rule=Host(`${HOST}`)"
      - "traefik.http.routers.zarabot.tls=true"
      - "traefik.http.routers.zarabot.tls.certresolver=leresolver"
      # - "traefik.http.routers.zarabot.middlewares=traefik-forward-auth"
