/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql";
export type getProxiesPage = {
    proxiesPage: {
        pagination: {
            page: number;
            rowsPerPage: number;
            rowsNumber: number;
        };
        rows: ({
            id: number;
            host: string;
            port: number;
            sources: ({
                source: {
                    name: string;
                };
                firstUpdate: {
                    updateTime: any;
                };
                lastUpdate: {
                    updateTime: any;
                };
            })[];
        })[];
    };
};
export type getProxiesPageVariables = {
    page: number;
    rowsPerPage: number;
};
export type getProxiesPageDocument = TypedQueryDocumentNode<getProxiesPage, getProxiesPageVariables>;
