/* eslint-disable */
/* This is an autogenerated file. Do not edit this file directly! */
import { TypedQueryDocumentNode } from "graphql";
export type knownHosts = {
    browserManagerState: {
        knownHosts: ({
            hostName: string;
            proxiesBlackList: string[] | null;
            proxiesBestList: ({
                proxyAddress: string;
                rating: number;
            })[] | null;
        })[];
    };
};
export type knownHostsVariables = {};
export type knownHostsDocument = TypedQueryDocumentNode<knownHosts, knownHostsVariables>;
